name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'JonaVDV/sveltekit-kql'
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          #this makes Actions fetch all git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build

      - name: Create Release PR or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
